name: Sync Dev branch with Main

# Trigger the workflow when there is a push to the main branch
on:
  push:
    branches: [main]
    
# Set permissions for the workflow to write to all repositories
permissions: write-all

jobs:
  sync:
    # Specify the environment in which the job will run
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches

      # Step 2: Set up Git user information for commits
      - name: Setup Git User
        env:
          USER: ${{ secrets.USER }} # Git username from secrets
          MAIL: ${{ secrets.MAIL }} # Git email from secrets
        run: |
          git config user.name "$USER" # Configure git username
          git config user.email "$MAIL" # Configure git email

      # Step 3: Update the dev branch with changes from the main branch
      - name: Update Dev Branch
        run: |
          git checkout main          # Switch to the main branch
          git fetch origin           # Fetch the latest changes from the remote
          git checkout dev           # Switch to the dev branch
          git pull                   # Pull the latest changes from the remote dev branch
          git merge origin/main      # Merge changes from the main branch into dev
          git push origin dev        # Push the updated dev branch to the remote
